
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.2-bionic
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key:  user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key:  password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key:  root_password
            - name: DATABASE_NAME
              value: 'django_app'
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysql-volume-mount
      volumes:
        - name: mysql-volume-mount
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
# Start Service - expose port
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    name: mysql
# Service END


