apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    app: mysql
type: Opaque
data:
  user: ZGphbmdvX3VzZXI=
  password: ZGphbmdvX2RiX3Bhc3N3b3Jk
  root_password: a2ljY2hpbg==
  db_name: ZGphbmdvX2FwcA==
