version: "3.9"
volumes:
  dbdata:
services:
  python:
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      TAG: 1.6
      DEBUG: ${DEBUG}
    env_file: 
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: django_app
      MYSQL_USER: django_user
      MYSQL_PASSWORD: BXsWTAbt9qfaHOgHMWdWc6Ntw
    volumes:
      - dbdata:/var/lib/mysql/django_app
    ports:
      - 3306:3306

  testcontainer:
    image: python:3.8-slim
    environment:
      TAG: 1.5
    env_file:
      - python.env
