version: "3.9"
services:
  python:
    image: django-dev:v1.0
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    command: python /app/manage.py runserver 0.0.0.0:8000


