version: "3.9"
volumes:
  dbdata:
  static_files:
services:
  python:
    image: django-dev:v1.0
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    volumes:
      - ./app:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    working_dir: /app
    command: cd /app && gunicorn -w 4 kittchen.pwsgi -b 0.0.0.0:8000
  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql/django_app
    ports:
      - 3306:3306
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8080:80

