# Generated by Django 3.1.3 on 2020-12-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='position',
        ),
    ]
