# Generated by Django 2.2.16 on 2020-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttable',
            name='unit',
            field=models.CharField(choices=[('millilitres', 'Millilitres'), ('Litres', 'Litres'), ('grams', 'Grams'), ('cup', 'Cup'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon')], default='millilitres', max_length=32),
        ),
    ]
