# Generated by Django 3.1.3 on 2020-11-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post'),
        ),
    ]
