# Generated by Django 2.2.16 on 2020-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredienttable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttable',
            name='unit',
            field=models.CharField(blank=True, choices=[('millilitres', 'Millilitres'), ('Litres', 'Litres'), ('grams', 'Grams'), ('cup', 'Cup'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon')], max_length=32),
        ),
    ]
