# Generated by Django 3.1.3 on 2020-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_direction_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serving_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
