# Generated by Django 2.2.16 on 2020-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201111_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttable',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Millilitres'), ('L', 'Litres'), ('g', 'Grams'), ('cup', 'Cup'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon')], max_length=32),
        ),
    ]
