# Generated by Django 3.1.3 on 2020-11-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201127_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
