# Generated by Django 3.1.3 on 2020-12-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_serving_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
