# Generated by Django 3.1.3 on 2020-12-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_servings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='serving_time',
            new_name='cooking_time',
        ),
    ]
