# Generated by Django 2.2.16 on 2020-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttable',
            name='unit',
            field=models.CharField(blank=True, choices=[('millilitres', 'ml'), ('Litres', 'L'), ('grams', 'g'), ('cup', 'cup'), ('teaspoon', 'tsp'), ('tablespoon', 'tbsp')], max_length=32),
        ),
    ]
