# Generated by Django 2.2.16 on 2020-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201111_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('body', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredienttable',
            name='quantity',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='directions',
            field=models.ManyToManyField(to='core.Direction'),
        ),
    ]
