# Generated by Django 2.2.16 on 2020-11-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201111_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='directions',
            new_name='direction',
        ),
        migrations.AddField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.Post'),
        ),
    ]
