# Generated by Django 2.2.16 on 2020-11-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201111_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.Post'),
        ),
    ]
