# Generated by Django 2.2.16 on 2020-11-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201111_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='direction',
        ),
    ]
