# Generated by Django 2.2.16 on 2020-11-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttable',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
