# Generated by Django 2.2.16 on 2020-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe-blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('millilitres', 'Millilitres'), ('Litres', 'Litres'), ('grams', 'Grams'), ('kilograms', 'Kilograms'), ('cup', 'Cup'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon')], default='millilitres', max_length=32)),
            ],
        ),
    ]
